name: Deployment to Netlify

on:
  push:
    branches:
      - master

jobs:
  deploy:
    name: Setup
    runs-on: ubuntu-latest

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: Setup Node
      uses: actions/setup-node@v2
      with: 
        node-version: 14.17.3
    - name: Build the website
      run: | 
        npm ci
        npm i @angular/cli -g
        ng build --prod
    - name: Deploy
      run: | 
        npm i -g netlify-cli
        netlify deploy --site ${{ secrets.NETLIFY_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir=dist/tic-tac-toev2 --prod